FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=build /app ./

EXPOSE 3000

CMD ["npm", "start"]


