services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://strapi:1337
      - NEXT_PUBLIC_STRAPI_MEDIA_URL=http://strapi:1337
      - STRAPI_API_URL=http://strapi:1337
    depends_on:
      - strapi
    networks:
      - webnet

  strapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./server/public/uploads:/app/public/uploads
      - ./server/.tmp:/app/.tmp # For SQLite persistence
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
      - strapi
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
