version: "3"
services:
  nextjs:
    build:
      context: ./client # Path to Next.js app
      dockerfile: Dockerfile # The Next.js Dockerfile
    ports:
      - "3000:3000" # Expose Next.js on port 3000
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://strapi:1337 # URL to Strapi
      - STRAPI_API_URL=http://strapi:1337
    depends_on:
      - strapi
    networks:
      - webnet

  strapi:
    build:
      context: ./server # Path to Strapi app
      dockerfile: Dockerfile # The Strapi Dockerfile
    ports:
      - "1337:1337" # Expose Strapi on port 1337
    volumes:
      - ./server/public/uploads:/app/public/uploads # Persist uploaded files
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db # SQLite DB persistence
    networks:
      - webnet

  nginx:
    image: nginx:alpine # Use a lightweight Nginx image
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount your Nginx config
    depends_on:
      - nextjs
      - strapi
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
